version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - hoodi

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - hoodi

  json-exporter:
    image: prometheuscommunity/json-exporter
    volumes:
      - ./json-config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
    ports:
      - "7979:7979"
    networks:
      - hoodi

networks:
  hoodi:
    external: true
    name: 2hoodi-node_default
